{"APP_ID":"wxe599ddfca42cb074","APP_SECRET":" 6c8425138705ba7a7dfcbef9475f8206",
"IS_SHOW_COLOR":true,
"USERS_INFO":[{"name":"Yue宝宝","id":"ov2176JF0lE1p5RGScYM0F6XpCxw",
"useTemplateId":"W42z6oKZe6FbEZMz9baSY2YBdX7SGaXqmTRQ4-kB_6Y",
"province":"辽宁","city":"大连",
"horoscopeDate":"09-11",
"horoscopeDateType":"今日",
"festivals":[{"type":"生日","name":"Yue宝宝的生日","date":"09-11","year":"1999"}],
"customizedDateList":[{"keyword":"我们在一起恋爱",
"date":"2021-08-29"}]}],"SWITCH":
{"weather":true,"holidaytts":false,
"CIBA":true,
"oneTalk":false,
"earthyLoveWords":true,"
momentCopyrighting":false,"
poisonChickenSoup":false,
"poetry":false,
"horoscope":true,
"birthdayMessage":true}}
